### ISSUE TITLE
binding error

### ISSUE THREAD

**Issue by wluker** [soegaard/urlang#11]
I don't know if you are still working on this, but I've been having fun playing with urlang and came across an error.

This definition in a urmodule:
````
(define a  
  (let ()
    (var [a (object)])
    (:= a "key" "val")
    a))
````
produces:
````
var a=((function(){var a_1={};(a["key"]="val");return a_1;})());
````

**Comment by soegaard** [comment]
Hi wluker,

Thanks for the bug report. I have committed a fix.

    https://github.com/soegaard/urlang/commit/88e9e356c434561c6fae06b083ba37021c318386

Urlang has been on a hiatus during the school year, but I have some ideas for the summer holiday :-)

If (when) you find other bugs, don't hesitate to report them.

/Jens Axel
