### ISSUE TITLE
multiple requires using the same MODULE var

### ISSUE THREAD

**Issue by wluker** [soegaard/urlang#13]
Requiring multiple modules produces javascript that has multiple `var MODULE =` instances.

Two modules:
````
(urlang
 (urmodule mod-a
   (export a)
   (define a 0))
 (urmodule mod-b
   (export b)
   (define b 1)))
````
And another module requiring both:
````
(urlang
 (urmodule test
   (require mod-a)
   (require mod-b)))
````
produces:
````
"use strict";
var MODULE = require("./mod-b.js");
var b = MODULE["b"];
var MODULE = require("./mod-a.js");
var a = MODULE["a"];
````
I don't know that this is necessarily a bug or even incorrect code, but some tools don't like it. Rollup (rollupjs.org) for example chokes on it with the error `[!] Error: Identifier 'MODULE' has already been declared`.

**Comment by soegaard** [comment]
Hi,

tir. 8. maj 2018 kl. 19.55 skrev wluker <notifications@github.com>:

> Requiring multiple modules produces javascript that has multiple var
> MODULE = instances.
>
> Two modules:
>
> (urlang
>  (urmodule mod-a
>    (export a)
>    (define a 0))
>  (urmodule mod-b
>    (export b)
>    (define b 1)))
>
> And another module requiring both:
>
> (urlang
>  (urmodule test
>    (require mod-a)
>    (require mod-b)))
>
> produces:
>
> "use strict";
> var MODULE = require("./mod-b.js");
> var b = MODULE["b"];
> var MODULE = require("./mod-a.js");
> var a = MODULE["a"];
>
> I don't know that this is necessarily a bug or even incorrect code, but
> some tools don't like it. Rollup (rollupjs.org) for example chokes on it
> with the error [!] Error: Idenptifier 'MODULE' has already been declared.
>

I'll need to do some investigating.

First, the specification allows multiple declarations of the same variable:
    https://www.ecma-international.org/ecma-262/6.0/#sec-variable-statement

    Within the scope of any VariableEnvironment
<https://www.ecma-international.org/ecma-262/6.0/#sec-execution-contexts> a
common BindingIdentifier
    may appear in more than one VariableDeclaration but those declarations
    collective define only one variable.

I am therefore inclined to say, that Rollup is more restrictive than it
needs to be.

However the problem might be that Urlang produces code suitable for the
NodeJS Runtime
from  https://nodejs.org/ . Being able to quickly test code directly in
DrRacket without
having to open a browser is very convenient. However the module system used
by Node is be slightly different from ES6 modules (which I believe are
expected by rollup).

Maybe the solution is to make a compiler switch so the user can choose the
type of output?

So far I have used   http://browserify.org/  to convert Node modules into
modules
usable by the browser.

Btw - I notice that the in the Raphael example, the code contains:


;; Keep the JavaScript "module system" happy in the browser

;; window.module = window.module || [];

(:= window.module (or window.module (array)))

/Jens Axel

**Comment by soegaard** [comment]
2018-05-08 19:55 GMT+02:00 wluker <notifications@github.com>:

> And another module requiring both:
>
> (urlang
>  (urmodule test
>    (require mod-a)
>    (require mod-b)))
>
> produces:
>
> "use strict";
> var MODULE = require("./mod-b.js");
> var b = MODULE["b"];
> var MODULE = require("./mod-a.js");
> var a = MODULE["a"];
>
>
I looked at the code generator, and it is easy to change it to generate
this instead:

> "use strict";
> var MODULE1 = require("./mod-b.js");
> var b = MODULE1["b"];
> var MODULE2 = require("./mod-a.js");
> var a = MODULE2["a"];
>
>
But - before I change it - will you test that this works with rollup ?

/Jens Axel

**Comment by wluker** [comment]
The above code : MODULE1, MODULE2 does seems to work for the rollup flow. 

I did some reading and you are correct that it is perfectly valid code to have variable re-declarations; even in strict mode. Rollup has to use a plugin to convert from commonJS modules (node) to the ES6 form that rollup expects. (https://github.com/rollup/rollup-plugin-commonjs) I expect it is this plugin/conversion that is causing the issue although I don't know for sure. If it is an easy fix to rename MODULE1...N, that seems like the best way forward for me. Certainly I don't want to ask you to work around every tool deficiency out there, but if any other potential users use rollup, then this change might be worth it.

As far as the commonJS versus ES6 module syntax... I don't know. I see the advantage to both, but maybe the node form provides more value right now. Supposedly the ES6 syntax provides for better tree-shaking within rollup, but I'm not an expert on that.

**Comment by soegaard** [comment]
@wluker 

Just committed a solution. Try it out and let me know if it works.

Example:

```
> (current-urlang-rollup? #t)
> (urlang
   (urmodule test
     (require mod-a)
     (require mod-b)))
"use strict";
var MODULE0 = require("./mod-b.js");
var b = MODULE0["b"];
var MODULE1 = require("./mod-a.js");
var a = MODULE1["a"];

```

**Comment by wluker** [comment]
Works well. Thank you.

**Comment by soegaard** [comment]
Great.
