### ISSUE TITLE
Failure while building urlang docs

### ISSUE THREAD

**Issue by jessealama** [soegaard/urlang#15]
(Working from commit: b6ceb75f8b5d82704919084d713d7da7da5a34b3)

urlang fails to build if the `html-parsing` package isn't installed:

    raco setup: error: during making for <pkgs>/urlang/urlang/html
    raco setup:   standard-module-name-resolver: collection not found
    raco setup:     for module path: html-parsing
    raco setup:     collection: "html-parsing"
    raco setup:     in collection directories:
    raco setup:      /Users/jessealama/Library/Racket/7.1/collects
    raco setup:      /Applications/Racket v7.1/collects
    raco setup:      ... [186 additional linked and package directories]
    raco setup:     compiling: <pkgs>/urlang/urlang/html/to-at-exp.rkt

There are a few more errors like this, all pointing to the absence of html-parsing.

Installing `html-parsing` does the job. It's enough to add `html-parsing` to `build-deps` in `info.rkt`.

**Comment by soegaard** [comment]
Good thing you reminded me off the build errors. 
I have made two commits, which I hope will get rid of the last commit errors.
We will have to wait till tomorrow to see what the build server says.

**Comment by soegaard** [comment]
Getting closer. Still an error from ffi.rkt. Commited a fix. Will check again tomorrow.

**Comment by soegaard** [comment]
Getting closer. Only dependency errors left. Commited a fix. Let's see what the build server says.

**Comment by soegaard** [comment]
Build server happy.
