### ISSUE TITLE
Creating a string in Racket and using it in Urlang

### ISSUE THREAD

**Issue by TheMrAmazing** [soegaard/urlang#29]
Hi, I'm playing around with Urlang coming from the Javascript world. My understanding is that is should be possible through macros to create a string (in something like the compile phase) that Urlang would be able to use. Here is my attempt:

(define-syntax m
  (syntax-rules ()
    [(_) (xexp->html `(html (head (title "Hello world!"))
          (body (p "Hey out there!"))))]))

 (urlang
 (urmodule demo-fact
       console.log(m)
  ))

but it seems it is not evaluating "m" right away as I thought it did. My understanding was that it would literally replace the macro with the result of the expression? How is this achieved?

**Comment by TheMrAmazing** [comment]
Thank you! That helps a lot. I have one more problem, I am trying to call a function window.customeElements.define() and I think it it is seeing the define as a keyword. Here is my code:

           `(import window)
           (var (str (testTemplate)))
           (class (customEl HTMLElement)
             ((x) 5)
             ((y) 7)
             )
           (var (customRegistry (dot window customElements)))
           (window.customElements.define ("custom-el" customEl))`

and it returns this error:
`parse-expr: expected an expression, got #<syntax:/frontend.rkt:42:12 define>
;   in: define
`

**Comment by soegaard** [comment]
Here is a workaround:

```
           (var (custom-elements-define (ref window.customElements "define")))
           (custom-elements-define  ("custom-el" customEl))
```

In JavaScript `define` is a keyword. It seems it is okay to use keywords as property names in JavaScript,
so you have found a bug in Urlang.

The workaround is get the `define` function using `(ref ... "define")` to avoid getting the keyword error.

I'll look into a fixing the bug.

**Comment by TheMrAmazing** [comment]
Awesome, thanks for your help, it's really cool project, I'm having a lot of fun playing around with it.
