### ISSUE TITLE
Can't `define` inside a `define`...

### ISSUE THREAD

**Issue by oofoe** [soegaard/urlang#33]
A common JavaScript idiom is to have a function that returns a namespace that includes other functions. This is a convenient way to encapsulate data:

```javascript
function varray(size, fill) {
    ...
    function dump() { console.dir(data); }
    ...
    return { dump, set, get };   
}
```

When I tried to do this in Urlang:

```racket
   (define (varray size fill)
       ...
       (define (dump) (console.dir data))
       ...
       (object [dump dump] [set set] [get get]))
```

It errored out on the interior `define` with:

```
square.rkt:153:8: parse-expr: expected an expression, got #<syntax:square.rkt:153:8 define>
  in: define
```

Thank you!

BTW, for reference, here's what I went with:
```racket
   (define (varray size fill)
     (let* ([size size]
            [stride-y (ref size 0)]
            [stride-z (* (ref size 0) (ref size 1))]
            [locate (λ (x y z) (+ x (* y stride-y) (* z stride-z)))]
            [data (Array.from
                   (object [length (* (ref size 0) (ref size 1) (ref size 2))])
                   (λ (e i) fill))])
       (object [dump (λ () (console.dir data))]
               [get  (λ (x y z) (ref data (locate x y z)))]
               [set  (λ (x y z v) (:= data (locate x y z) v))]
               )
       ))
```

**Comment by soegaard** [comment]
Not allowing `define` in a function body was done on purpose. If I recall correctly, the scope rules for `define` at the top-level are subtly different from local definitions. 

So, instead one must use `var` to define a local function.  In my own code, I use this little macro to define a `def` that allows one to use both `(define name expr)` and `(define (name arg ...) . body)` in a local context.

```
(define-urlang-macro def
  (λ (stx)
    (syntax-parse stx
      [(_def (name arg ...) . body)
       (syntax/loc stx
         (var [name (λ (arg ...) . body)]))]
      [(_def name expr)
       (syntax/loc stx
         (var [name expr]))])))
```

**Comment by oofoe** [comment]
OK, understood. Thanks very much for taking a look! Will try that.
