### ISSUE TITLE
Urlang won't work with NodeJS on Windows

### ISSUE THREAD

**Issue by gregid** [soegaard/urlang#9]
Running Urlang file with Node (current-urlang-run #t) or any node modules (babel, js-beautify) will result in an error:
"System can't find the path specified"

**Comment by soegaard** [comment]
Hi Gregid,

Just checking:  Have you installed Node from https://nodejs.org/en/ ?
If you have, what OS are you on - and what are the default path on
your system?

The path to Node is currently hard coded to /usr/local/bin/node and
Babel to: /usr/local/bin/babel 

I need to turn the paths into parameters, so users can changes them - in the
mean time, you can change the paths by opening urlang/main.rkt . 
The path to Node is on line 2170 and the path to Babel is little further down.

https://github.com/soegaard/urlang/blob/master/urlang/main.rkt#L2170

/Jens Axel

**Comment by gregid** [comment]
Thanks,
Yes I've noticed the path is hard coded in main.rkt, so making paths into parameters would be a good idea.
The default path when using windows (Win 10) installer is:
C:\Program Files\nodejs\
For babel:
C:\Program Files\nodejs\babel -> C:\Program Files\nodejs\node_modules\babel-cli\bin\babel.js
For js-beautify:
C:\Program Files\nodejs\js-beautify -> C:\Program Files\nodejs\node_modules\js-beautify\js\bin\js-beautify.js

I think it's reasonable to assume "C:\Program Files\nodejs\" will be default path on most Windows versions

**Comment by gregid** [comment]
With the change of path js-beautify works with no problem, still sorting out paths for babel presets, but running on nodejs example file: quiz.rkt gives me the following error:
```
E:\RacketProjects\RacketWebTutorial\UrlangTests\quiz\quiz.js:4

var $answer_input = ($("#answer-input"));

                     ^



ReferenceError: $ is not defined

    at Object.<anonymous> (E:\RacketProjects\RacketWebTutorial\UrlangTests\quiz\quiz.js:4:22)

    at Module._compile (module.js:570:32)

    at Object.Module._extensions..js (module.js:579:10)

    at Module.load (module.js:487:32)

    at tryModuleLoad (module.js:446:12)

    at Function.Module._load (module.js:438:3)

    at Module.runMain (module.js:604:10)

    at run (bootstrap_node.js:389:7)

    at startup (bootstrap_node.js:149:9)

    at bootstrap_node.js:504:3
```

nodejs version I am using is v6.11.1

**Comment by soegaard** [comment]
That example is meant to be run in the browser. Running `quiz.rkt` produces both an html and an js file.  Open "quiz.rkt" in DrRacket and click run. The program should open the html page automatically in a browser. Details: the last expression in `quiz.rkt` is:

    (send-url/contents
     (generate-html
      @~xs{ @navigation-bar[]
            @comment{Use a container to make the footer and the row the same width}
            @container[@html-flash-card-row]
            @container[@html-the-footer]
            @comment{This div has a hidden list of all question-answer pairs}
            @div[id: "card-db" style: "display: none"
                 (map card->html cards)]}
      "quiz.js"))

and `send-url/contents` ought to start the browser. On macOS there is currently a bug (in macOS not Racket)  that stops DrRacket from opening the browser. If that happens to you let me know. If it does happen, you should get an error with the name of the html file. Just open the html file in the browser.

Also: When you enter an incorrect answer in the quiz, the correct answer is printed in the text input field. Now enter the answer exactly as it is written and press enter to continue. This isn't clear from the page (I was trying to mimic the excellent web page lingvist.com )

**Comment by gregid** [comment]
Thank you for the explanation. I can run the examples directly in the browser (which is great) and what I was trying to figure out was how to use Urlang with nodejs. It seems I may have misunderstood the purpose of "run on node". I simply assumed this will serve the website from nodejs server. Instead this will simply execute the expanded javascript code via node (as in demo-fact.rkt example).

Thank you for your work on Urlang and compiler-rjs - looking forward to seeing the final result of your work!

**Comment by soegaard** [comment]
Hi Greg,

While developing Urlang programs it is convenient to run them directly in Node.
I haven't experimented with the Node web-server yet, but it is certainly also possible
to simple write the generated JavaScript to a file and let the Node web-server handle
serving the client with html+js.

The Racket to JavaScript compiler is taking form. The major piece missing from the puzzle right now are modules. Working on it... 

/Jens Axel
